### ISSUE TITLE
"Kafka version" parameter in OpenShift template

### ISSUE THREAD

**Issue by scholzj** [EnMasseProject/barnabas#19]
The `openshift_tamplate.yaml` for Kafka Statefull set seems to contain following parameter which is not used:
```yaml
- description: Kafka Version
  displayName: Kafka Version
  name: KAFKA_VERSION
  value: "0.11.0.0"
```

We should clarify its purpose and either remove it or use it. Wa sit supposed to determine the image version?
