### ISSUE TITLE
Can't work on kubernetes/minikube

### ISSUE THREAD

**Issue by leenux** [EnMasseProject/barnabas#72]
```bash
# kubectl apply -f kafka-statefulsets/resources/cluster-volumes.yaml
persistentvolume "pv0001" created
persistentvolume "pv0002" created
persistentvolume "pv0003" created
persistentvolume "pv0004" created
Error from server (Invalid): PersistentVolume "pv0005" is invalid: spec.accessModes: Required value
Error from server (Invalid): PersistentVolume "pv0006" is invalid: spec.accessModes: Required value
```
after insert kafka-statefulsets/resources/cluster-volumes.yaml by editor
```
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv0005
  spec:
    capacity:
      storage: 5Gi
```
###      - ReadWriteOnce
```
   persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /tmp/pv0005
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv0006
  spec:
    capacity:
      storage: 5Gi
```
###      - ReadWriteOnce
```
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /tmp/pv0006
```
this yaml work fine.
but run `kubectl apply -f kafka-statefulsets/resources/zookeeper.yaml`
`error: error converting YAML to JSON: yaml: line 34: did not find expected key`
and I swap between `name: clientport` and `containerPort: 2181`
```
            - name: clientport
              containerPort: 2181
              protocol: TCP
```
The error was same ``error: error converting YAML to JSON: yaml: line 34: did not find expected key`
How to do the work?
Env:
```
# minikube version
minikube version: v0.22.3
# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-07T00:39:16Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
